version: '3.7'
services:
  db:
    image: mongo:5.0.0-focal
    restart: always
    environment:
      # Database credentials.
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev
    networks:
      - db
    volumes:
      - db

  # Admin UI for mongo db. Not required.
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 127.0.0.1:8081:8081
    environment:
      # Database address.
      ME_CONFIG_MONGODB_SERVER: db
      # Database credentials.
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev
      # Web UI credentials.
      # ME_CONFIG_BASICAUTH_USERNAME: root
      # ME_CONFIG_BASICAUTH_PASSWORD: dev
    networks:
      - db
      - outbound

  ramranch-api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: ramranch-api:dev
    init: true # Node.js is not meant to run as PID 1, this spawns tini.
    environment:
      NODE_ENV: development
      API_LISTEN_PORT: 3001
      MONGO_HOST: db
      MONGO_USER: root
      MONGO_PASSWORD: dev
      JWT_SECRET_KEY: ce6ca078ddc3c06c0c3fd11f158b63e6c947c084219c2b28604f58e009cf7977
    networks:
      - db
      - outbound

  ramranch-web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: ramranch-web:dev
    ports:
      - 3002:80
    networks:
      - outbound

networks:
  db:
    internal: true
  outbound:

volumes:
  db:
