version: '3.8'
services:
  db:
    image: mongo:5.0.0-focal
    restart: always
    environment:
      # Database credentials.
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev
    networks:
      - db
    volumes:
      - db

  # Admin UI for mongo db. Not required.
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports: 
      - 8081:8081
    environment:
      # Database address.
      ME_CONFIG_MONGODB_SERVER: db
      # Database credentials.
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev
      # Web UI credentials.
      # ME_CONFIG_BASICAUTH_USERNAME: root
      # ME_CONFIG_BASICAUTH_PASSWORD: dev
    networks:
      - db
      - outbound

  ramranch-api:
    build: ./backend
    image: ramranch-api:dev
    init: true # Node.js is not meant to run as PID 1, this spawns tini.
    ports:
      - 3001:3001
    environment:
      NODE_ENV: development
      API_LISTEN_PORT: 3001
      MONGO_HOSTS: db
      MONGO_USER: root
      MONGO_PASSWORD: dev
    networks:
      - db
      - outbound

  ramranch-web:
    build: ./frontend
    image: ramranch-web:dev
    ports:
      - 3002:80
    networks:
      - outbound

networks:
  db:
    internal: true
  outbound:

volumes:
  db:
